name: Andrew Perry
url: http://andrewperry.us
baseurl: /andrewperry

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'autolink']

pygments: true

exclude: ["README.md", "config.rb", "andrewperry.sublime-project", "andrewperry.sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache"]
